export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const LIST_EVENT_REQUEST = "LIST_EVENT_REQUEST";
export const LIST_EVENT_SUCCESS = "LIST_EVENT_SUCCESS";
export const LIST_EVENT_FAIL = "LIST_EVENT_FAIL";
