export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const LIST_EVENTS_REQUEST = "LIST_EVENTS_REQUEST";
export const LIST_EVENTS_SUCCESS = "LIST_EVENTS_SUCCESS";
export const LIST_EVENTS_FAIL = "LIST_EVENTS_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";
